name: Deploy to EC2

on:
  push:
    branches:
      - main

env:
  AWS_REGION: MY_AWS_REGION               # Define a região da AWS
  EC2_INSTANCE_ID: MY_EC2_INSTANCE_ID     # ID da instância EC2
  EC2_PUBLIC_DNS: MY_EC2_PUBLIC_DNS       # DNS público da instância EC2
  SSH_KEY: ${{ secrets.EC2_SSH_KEY }}     # Chave SSH para acessar a instância EC2
  APP_DIRECTORY: /path/to/app             # Caminho para o diretório da aplicação na instância EC2
  REPO_URL: https://github.com/akillez01/projeto-final-ada-achilles.git # URL do repositório
  BRANCH_NAME: main                       # Nome da branch que você está fazendo o deploy

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ env.EC2_PUBLIC_DNS }} << 'EOF'
          # Atualize o repositório
          cd $APP_DIRECTORY
          git pull origin $BRANCH_NAME
          
          # Instale as dependências e reinicie a aplicação
          # (ajuste os comandos conforme necessário para sua aplicação)
          pip install -r requirements.txt
          sudo systemctl restart myapp.service
        EOF
