name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Launch EC2 instance
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        # Verifica se a instância já existe
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=projetoada" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)

        if [ -z "$INSTANCE_ID" ]; then
          echo "No instance found. Creating a new EC2 instance..."
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0182f373e66f89c85 \
            --instance-type t2.micro \
            --key-name scada \
            --security-group-ids sg-05ca68f43ee4e7002 \
            --subnet-id subnet-0d57bd52b47b13707 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=projetoada}]' \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "EC2 instance created with ID: $INSTANCE_ID"
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        else
          echo "Instance already exists with ID: $INSTANCE_ID"
        fi

        # Pegar o IP público da instância
        INSTANCE_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)

        echo "EC2 instance is running at: $INSTANCE_IP"
        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

    - name: Deploy to EC2
      env:
        AWS_EC2_IP: ${{ env.INSTANCE_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      run: |
        # Add SSH key
        echo "$SSH_PRIVATE_KEY" > ssh_key.pem
        chmod 400 ssh_key.pem

        # Deploy to EC2
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ec2-user@$AWS_EC2_IP << 'EOF'
        
          # Atualiza os pacotes
          sudo yum update -y

          # Instala o Python e os pacotes necessários
          sudo yum install python3 -y
          pip3 install --user -r /home/ec2-user/projeto-final-ada/requirements.txt

          # Instala e configura o Nginx
          sudo yum install nginx -y
          sudo systemctl start nginx
          sudo systemctl enable nginx

          # Configura o proxy reverso do Nginx
          sudo bash -c 'cat > /etc/nginx/conf.d/default.conf <<EOL
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }
          EOL'
          sudo systemctl restart nginx

          # Inicia a aplicação Python
          nohup python3 /home/ec2-user/projeto-final-ada/app.py > output.log 2>&1 &

        EOF