name: Deploy no EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Launch EC2 instance
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        # Verifica se a instância já existe
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=projetoada" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)

        if [ -z "$INSTANCE_ID" ]; then
          echo "No instance found. Creating a new EC2 instance..."
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0182f373e66f89c85 \
            --instance-type t2.micro \
            --key-name scada \
            --security-group-ids sg-05ca68f43ee4e7002 \
            --subnet-id subnet-0d57bd52b47b13707 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=projetoada}]' \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "EC2 instance created with ID: $INSTANCE_ID"
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        else
          echo "Instance already exists with ID: $INSTANCE_ID"
        fi

        # Pegar o IP público da instância
        INSTANCE_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)

        echo "EC2 instance is running at: $INSTANCE_IP"
        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

    - name: Deploy to EC2
      env:
        AWS_EC2_IP: ${{ env.INSTANCE_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        # Add SSH key
        echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key.pem
        chmod 600 /tmp/ssh_key.pem

        # Conectar na instância EC2 via SSH e executar os comandos de deploy
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key.pem ec2-user@$AWS_EC2_IP << EOF

          # Atualizar pacotes e instalar Python3
          sudo yum update -y
          sudo yum install python3 -y
          sudo yum install python3-pip -y
          sudo yun install git -y

          # Instalar pip3 e criar virtualenv para a aplicação
          sudo pip3 install virtualenv
          if [ ! -d "/home/ec2-user/myenv" ]; then
            virtualenv /home/ec2-user/myenv
          fi

          # Ativar o ambiente virtual e instalar as dependências
          git clone https://github.com/viniciuscaol/projeto-final-ada.git
          cd /home/ec2-user/projeto-final-ada/
          pip install -r requirements.txt

          # Parar a aplicação se estiver rodando na porta 80
          sudo fuser -k 80/tcp || true

          # Executar a aplicação Flask na porta 80
          nohup python3 app.py --host=0.0.0.0 --port=80 > /home/ec2-user/projeto-final-ada/output.log 2>&1 &
        EOF
