on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli

    - name: Launch EC2 instance
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        # Verifica se a instância já existe
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=projetoada" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)

        if [ -z "$INSTANCE_ID" ]; then
          echo "No instance found. Creating a new EC2 instance..."
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0182f373e66f89c85 \
            --instance-type t2.micro \
            --key-name scada \
            --security-group-ids sg-05ca68f43ee4e7002 \
            --subnet-id subnet-0d57bd52b47b13707 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=projetoada}]' \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "EC2 instance created with ID: $INSTANCE_ID"
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
        else
          echo "Instance already exists with ID: $INSTANCE_ID"
        fi

        # Pegar o IP público da instância
        INSTANCE_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)

        echo "EC2 instance is running at: $INSTANCE_IP"
        echo "INSTANCE_IP=$INSTANCE_IP" >> $GITHUB_ENV

    - name: Deploy Docker to EC2
      env:
        AWS_EC2_IP: ${{ env.INSTANCE_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        # Add SSH key
        echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key.pem
        chmod 600 /tmp/ssh_key.pem

         # Conectar na instância EC2 via SSH e executar os comandos de deploy
        ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key.pem ec2-user@$AWS_EC2_IP << EOF
          
          # Atualizar pacotes e instalar Python3 e Nginx
          sudo yum update -y
          sudo yum install python3 nginx -y

          # Instalar pip3 e criar virtualenv para a aplicação
          sudo pip3 install virtualenv
          if [ ! -d "/home/ec2-user/myenv" ]; then
            virtualenv /home/ec2-user/myenv
          fi

          # Ativar o ambiente virtual e instalar as dependências
          source /home/ec2-user/myenv/bin/activate
          cd /home/ec2-user/app
          pip install -r requirements.txt

          # Configurar Nginx como proxy reverso
          sudo bash -c 'cat > /etc/nginx/conf.d/flask_app.conf <<EOL
          server {
              listen 80;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }
          EOL'
          sudo systemctl restart nginx

          # Parar a aplicação se estiver rodando na porta 5000
          fuser -k 5000/tcp || true

          # Executar a aplicação Flask em background na porta 5000
          nohup python3 /home/ec2-user/app/app.py > /home/ec2-user/app/output.log 2>&1 &
        EOF