name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      run: |
        # Add SSH key
        echo "$SSH_PRIVATE_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem

        # Deploy to EC2
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ec2-user@$AWS_EC2_IP << 'EOF'
        
          # Atualiza os pacotes
          sudo yum update -y

          # Instala o Python e os pacotes necessários
          sudo yum install python3 -y
          pip3 install --user -r /home/ec2-user/projeto-final-ada/requirements.txt

          # Configura o Nginx
          sudo yum install nginx -y
          sudo systemctl start nginx
          sudo systemctl enable nginx

          # Configura o proxy reverso do Nginx
          sudo bash -c 'cat > /etc/nginx/conf.d/default.conf <<EOL
          server {
              listen 80;
              server_name _;
              
              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
                  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto \$scheme;
              }
          }
          EOL'
          sudo systemctl restart nginx

          # Inicia a aplicação Python
          nohup python3 /home/ec2-user/projeto-final-ada/app.py > output.log 2>&1 &

        EOF