name: Deploy e Testar Aplicação

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ajuste para a versão de Python que você está usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the application
        run: |
          nohup python app.py &  # Ou qualquer outro comando para iniciar sua aplicação
          sleep 10  # Aguarda 10 segundos para garantir que a aplicação está rodando

      - name: Test the application
        run: |
          curl -f http://localhost:5000  # Ajuste a URL e porta conforme sua configuração
